### ISSUE TITLE
pptx.exc.PackageNotFoundError: Package not found at 'static/presentations/simple.pptx'

### ISSUE THREAD

**Issue by pedroaugustoramos** [otahina/PowerPoint-Generator-Python-Project#12]
Hi, Hina
Congratulation on the beautiful app. I'm trying to run it, but it seems that when it is the time to the ppt be generated, the error arises: pptx.exc.PackageNotFoundError: Package not found at 'static/presentations/simple.pptx'
the simple and the other pptx files are opening correctly in my ppt app. I use mac.
Any thoughts for the solution? Thank you very much

**Comment by pedroaugustoramos** [comment]
I'm using your last version

**Comment by pedroaugustoramos** [comment]
python version is 3.11.6

**Comment by pedroaugustoramos** [comment]
python version I'm using is 3.11.6

**Comment by pedroaugustoramos** [comment]
I also tried with python version 3.9, but the same error occurs

**Comment by pedroaugustoramos** [comment]
Never mind! I resolved the issue by changing the create_ppt function with the absolute path ->  template_path = os.path.join(current_app.root_path, 'static', 'presentations', f"{template_choice}.pptx")
Did the same thing for the output path -> output_path = os.path.join(current_app.root_path, 'generated', 'generated_presentation.pptx')

    # Save the presentation
    prs.save(output_path) Then it worked properly. The problem seems to be with flask. Thank you!

**Comment by pedroaugustoramos** [comment]
template_path = os.path.join(current_app.root_path, 'static', 'presentations', f"{template_choice}.pptx")

    prs = Presentation(template_path)

**Comment by changchiyou** [comment]
You must follow the steps in [How to use](https://github.com/otahina/PowerPoint-Generator-Python-Project?tab=readme-ov-file#how-to-use) section:

> Navigate to `myapp` directory. Run `flaskapp.py`
>
> ```
> python3 myapp/flaskapp.py
> ```

Especialy 「Navigate to `myapp` directory.」.
