### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by moonzaidi7262** [otahina/PowerPoint-Generator-Python-Project#6]
when i click create presentation after select the theme i got this error!!

<img width="960" alt="Capture" src="https://github.com/otahina/PowerPoint-Generator-Python-Project/assets/111485738/72832358-3986-4406-9ef8-b2d9a9393c6d">
<img width="959" alt="2" src="https://github.com/otahina/PowerPoint-Generator-Python-Project/assets/111485738/db71ece2-5134-4c01-b4c5-9b29c5d2fd75">

**Comment by moonzaidi7262** [comment]
![Uploading 2.PNG…]()

**Comment by moonzaidi7262** [comment]
in text_pp.py file change your parse_response function with this following code good luck

def parse_response(response):
    slides = response.split('\n\n')
    slides_content = []
    for slide in slides:
        lines = slide.split('\n')
        title_line = lines[0]
        if ': ' in title_line:
            title = title_line.split(': ', 1)[1]  # Extract the title after 'Slide X: '
        else:
            title = title_line
        content_lines = [line for line in lines[1:] if line != 'Content:']  # Skip line if it is 'Content:'
        content = '\n'.join(content_lines)  # Join the lines to form the content
        # Extract the keyword from the line that starts with 'Keyword:' or 'Keywords:'
        keyword_lines = [line for line in lines if 'Keyword:' in line or 'Keywords:' in line]
        if keyword_lines:
            keyword_line = keyword_lines[0]
            keyword = keyword_line.split(': ', 1)[1]
        else:
            keyword = ""  # Set a default value if no keyword is found
        slides_content.append({'title': title, 'content': content, 'keyword': keyword})
    return slides_content

**Comment by otahina** [comment]
I'll check it out and fix it, thank for pointing out! :)

**Comment by moonzaidi7262** [comment]
Yeah Sure i hope you will add more features in this web app

**Comment by otahina** [comment]
Feel free to make a pull request or issues, and be a contributor of the project!

**Comment by otahina** [comment]
If you check the terminal, gpt response looks like this.(content is just one example)
Slide 1: Introduction to Information Technology
Content:
- Definition and importance of Information Technology
- Role of IT in businesses and organizations
- Various components and applications of IT
- Benefits of adopting IT in the workplace
Keywords: Information Technology, Introduction

Slide 2: Emerging Trends in Information Technology
Content:
- Cloud computing and its advantages
- Artificial Intelligence and machine learning
- Internet of Things and its implications
- Big Data and analytics
Keywords: Emerging Trends, Information Technology

And if the format is like Slide<slide_number>: Content: <something...> Keywords:<something...> so can you check the terminal? If you can see this format, you are supposed to generate powerpoint. Keyword is used for querying the image. After you check this, let me know the result 👍

**Comment by moonzaidi7262** [comment]
okkk sure
